
// This file was automatically generated by the Dapper.FastCRUD T4 Template
// Do not make changes directly to this file - edit the template configuration instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `EntityGeneration`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `server=192.168.2.21;database=rrk_shortvideo;uid=sa; pwd=Ftgj888888`
//     Include Views:          `True`

namespace Dapper.FastCrud.Tests.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the tb_shortVideo_userLock table.
    /// </summary>
	[Table("tb_shortVideo_userLock")]
	public partial class tbshortVideouserLock
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual long userId { get; set; }
	    public virtual DateTime createTime { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_search_hotkey table.
    /// </summary>
	[Table("tb_search_hotkey")]
	public partial class tbsearchhotkey
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual string key { get; set; }
	    public virtual int hot { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_short_video_share table.
    /// </summary>
	[Table("tb_short_video_share")]
	public partial class tbshortvideoshare
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual long userId { get; set; }
	    public virtual long shortVideoId { get; set; }
	    public virtual string shareCode { get; set; }
	    public virtual string shareTo { get; set; }
	    public virtual DateTime shareTime { get; set; }
	    public virtual DateTime expirationTime { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_short_video_class table.
    /// </summary>
	[Table("tb_short_video_class")]
	public partial class tbshortvideoclass
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual string name { get; set; }
	    public virtual string iconUrl { get; set; }
	    public virtual int orderIndex { get; set; }
	    public virtual DateTime createTime { get; set; }
	    public virtual int isShow { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_short_video_review table.
    /// </summary>
	[Table("tb_short_video_review")]
	public partial class tbshortvideoreview
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual long shortVideoId { get; set; }
	    public virtual int reviewStatus { get; set; }
	    public virtual long? reviewUserid { get; set; }
	    public virtual string memo { get; set; }
	    public virtual DateTime? reviewTime { get; set; }
	    public virtual DateTime createTime { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_short_video_report table.
    /// </summary>
	[Table("tb_short_video_report")]
	public partial class tbshortvideoreport
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual long shortVideoId { get; set; }
	    public virtual long userId { get; set; }
	    public virtual int type { get; set; }
	    public virtual string content { get; set; }
	    public virtual DateTime createTime { get; set; }
	    public virtual string picture { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_short_video_praise table.
    /// </summary>
	[Table("tb_short_video_praise")]
	public partial class tbshortvideopraise
	{
	    public virtual long userId { get; set; }
	    public virtual long shortVideoId { get; set; }
	    public virtual DateTime createTime { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_short_video_view table.
    /// </summary>
	[Table("tb_short_video_view")]
	public partial class tbshortvideoview
	{
	    public virtual long userId { get; set; }
	    public virtual long shortVideoId { get; set; }
	    public virtual DateTime createTime { get; set; }
	    public virtual string clientType { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_shortVideo_shotItem_android table.
    /// </summary>
	[Table("tb_shortVideo_shotItem_android")]
	public partial class tbshortVideoshotItemandroid
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual string title { get; set; }
	    public virtual string itemUrl { get; set; }
	    public virtual string iconUrl { get; set; }
	    public virtual int orderIndex { get; set; }
	    public virtual long classId { get; set; }
	    public virtual DateTime createTime { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_shortVideo_shotItem_ios table.
    /// </summary>
	[Table("tb_shortVideo_shotItem_ios")]
	public partial class tbshortVideoshotItemio
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual string title { get; set; }
	    public virtual string itemUrl { get; set; }
	    public virtual string iconUrl { get; set; }
	    public virtual int orderIndex { get; set; }
	    public virtual long classId { get; set; }
	    public virtual DateTime createTime { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_bg_music table.
    /// </summary>
	[Table("tb_bg_music")]
	public partial class tbbgmusic
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual string name { get; set; }
	    public virtual string author { get; set; }
	    public virtual long? userId { get; set; }
	    public virtual int isOriginal { get; set; }
	    public virtual string fileUrl { get; set; }
	    public virtual int classid { get; set; }
	    public virtual DateTime createTime { get; set; }
	    public virtual int? count { get; set; }
	    public virtual string picture { get; set; }
	    public virtual int length { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_comment_report table.
    /// </summary>
	[Table("tb_comment_report")]
	public partial class tbcommentreport
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual long commentId { get; set; }
	    public virtual long userId { get; set; }
	    public virtual int type { get; set; }
	    public virtual string content { get; set; }
	    public virtual DateTime createTime { get; set; }
	    public virtual string picture { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_comment_praise table.
    /// </summary>
	[Table("tb_comment_praise")]
	public partial class tbcommentpraise
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual long commentId { get; set; }
	    public virtual long userId { get; set; }
	    public virtual DateTime createTime { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_shortVideo_item_class table.
    /// </summary>
	[Table("tb_shortVideo_item_class")]
	public partial class tbshortVideoitemclass
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual string name { get; set; }
	    public virtual string iconUrl { get; set; }
	    public virtual int orderIndex { get; set; }
	    public virtual DateTime createTime { get; set; }
	    public virtual int isShow { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_bg_music_class table.
    /// </summary>
	[Table("tb_bg_music_class")]
	public partial class tbbgmusicclass
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual string name { get; set; }
	    public virtual string iconUrl { get; set; }
	    public virtual int orderIndex { get; set; }
	    public virtual DateTime createTime { get; set; }
	    public virtual int isShow { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_bg_music_review table.
    /// </summary>
	[Table("tb_bg_music_review")]
	public partial class tbbgmusicreview
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual long musicId { get; set; }
	    public virtual int reviewStatus { get; set; }
	    public virtual long? reviewUserid { get; set; }
	    public virtual string memo { get; set; }
	    public virtual DateTime? reviewTime { get; set; }
	    public virtual DateTime createTime { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_bg_music_report table.
    /// </summary>
	[Table("tb_bg_music_report")]
	public partial class tbbgmusicreport
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual long musicId { get; set; }
	    public virtual long userId { get; set; }
	    public virtual int type { get; set; }
	    public virtual string content { get; set; }
	    public virtual DateTime createTime { get; set; }
	    public virtual string picture { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_bg_music_favorite table.
    /// </summary>
	[Table("tb_bg_music_favorite")]
	public partial class tbbgmusicfavorite
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual long musicId { get; set; }
	    public virtual long userId { get; set; }
	    public virtual DateTime createTime { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_shortVideo table.
    /// </summary>
	[Table("tb_shortVideo")]
	public partial class tbshortVideo
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual string fileUrl { get; set; }
	    public virtual string screenFileUrl { get; set; }
	    public virtual int length { get; set; }
	    public virtual long userId { get; set; }
	    public virtual long? goodsId { get; set; }
	    public virtual DateTime createTime { get; set; }
	    public virtual string uploadClientType { get; set; }
	    public virtual DateTime uploadTime { get; set; }
	    public virtual string title { get; set; }
	    public virtual long musicId { get; set; }
	    public virtual long classId { get; set; }
	    public virtual int isPrivate { get; set; }
	    public virtual float x { get; set; }
	    public virtual float y { get; set; }
	    public virtual int citycode { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_comment table.
    /// </summary>
	[Table("tb_comment")]
	public partial class tbcomment
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual long userId { get; set; }
	    public virtual long videoId { get; set; }
	    public virtual string content { get; set; }
	    public virtual DateTime createTime { get; set; }
	    public virtual DateTime? modifiedTime { get; set; }
	    public virtual int? quoteid { get; set; }
	    public virtual string quoteContent { get; set; }
	    public virtual int status { get; set; }
	}

    /// <summary>
    /// A class which represents the tb_short_video_tag table.
    /// </summary>
	[Table("tb_short_video_tag")]
	public partial class tbshortvideotag
	{
		[Key]
	    public virtual long shortvideoid { get; set; }
	    public virtual string tags { get; set; }
	}

}

