//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.Bill
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyer
    {
        public long ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Mail { get; set; }
        public string Bank { get; set; }
        public string SubBank { get; set; }
        public string BankNumber { get; set; }
        public string BankNumberPersonName { get; set; }
        public int SellerLevel { get; set; }
        public Nullable<int> IsAuthentication { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
    }
}
