//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.Bill
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class billEntities : DbContext
    {
        public billEntities()
            : base("name=billEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buyer> buyers { get; set; }
        public virtual DbSet<good> goods { get; set; }
        public virtual DbSet<preorder> preorders { get; set; }
        public virtual DbSet<seller> sellers { get; set; }
    }
}
