//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZP.Bill
{
    using System;
    using System.Collections.Generic;
    
    public partial class preorder
    {
        public long ID { get; set; }
        public long GoodsID { get; set; }
        public long BuyerID { get; set; }
        public int PreState { get; set; }
        public string GoodsPictureUrl { get; set; }
        public string EvaluatePictureUrl { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Memo { get; set; }
    }
}
